name = "mxs-demo-account-worker"
main = "src/index.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-03-04"
workers_dev = false
minify = true

kv_namespaces = [
	{ binding = "MFARequiredTokens_DEMO", id = "afe17ed595224defae86a47e9d4f89f5" },
	{ binding = "LogtoAccessToken_DEMO", id = "fd6bd0bbc30847aea099b40404587a5b" },
	{ binding = "UsernameChangeTimelimit_DEMO", id = "27676d7055804c07bd533afedfda36db" }
]

[vars]
AVATAR_API = "https://check.mxs.app"
CORS = "https://demo-id.mxs.app"
ISSUER = "https://logto-development.mxs.app/oidc"
JWKS_URI = "https://logto-development.mxs.app/oidc/jwks"
LOGTO_DOMAIN = "https://logto-development.mxs.app"
LOGTO_CORE_RESOURCE = "https://v32424.logto.app/api"
ENABLE_NSFW_CHECK = 1

[triggers]
crons = ["0 */2 * * *"]

[placement]
mode = "smart"
